### ISSUE TITLE
Is this the firmware for ...?

### ISSUE THREAD

**Issue by RHeijmann** [jumbo77/portapackh2#1]
Hi Jumbo077,

Is this the firmware for: https://nl.aliexpress.com/item/4000907775687.html?spm=a2g0o.9042311.0.0.38c34c4dkQm47R

The original instruction refers to: https://github.com/jumbo077/portapack-havoc/blob/master/portapack-havoc.rar
But this one does not work.

Could you tell me what the changes are between yours and the latest version of Eried?

Kind regards,

Rik Heijmann

**Comment by jumbo77** [comment]
Hi, It is for Lusya's H2 the link
that instrution is not work.
Just Find new on https://github.com/jumbo77/portapackh2

**Comment by jumbo77** [comment]
the link is wrong{ https://github.com/jumbo077/portapack-havoc/blob/master/portapack-havoc.rar  }

**Comment by RHeijmann** [comment]
Thanks :). 

I have successfully  flashed my portapack with your newest firmware.

If you need someone to test your new firmware please send me a message. I have added you on discord. At least this should be your discord handle: BG7IYN#xxxx
