### ISSUE TITLE
Upgrading to 1.5.3

### ISSUE THREAD

**Issue by furkankesgin** [jumbo77/portapackh2#7]
Hi, I want to use the latest version of portapack h2 software but the problem is that, when I installing the software screen stuck on black screen. I can just install the your latest one which is the 1.4.2. Is it possible to explain how we can make update by ourself without black screen? Or Is it possible to make your magic for the latest one :)

**Comment by onetechct** [comment]
Same problem with a H2+..Now not work with last version, black sreeen. Can use only 1.4.3 👍 https://github.com/jumbo77/portapackh2/releases/tag/FW3

**Comment by furkankesgin** [comment]
Thank you very much @onetechct 🙏 for this help, I really appreciated it. It works on me.
If anyone got a black screen after uploading the firmware, check if it is inside 1.5.3 firmware. If there are, first disconnect your device from the computer and you need to close your device by hold pressing the left button(Big button). After the device is completely powered off, hold the mini left button then hold the left big button. It works like this on me.
